version: "3.9"

volumes:
  mysql-data:

x-env: &env
  environment:
    - BOT_USERNAME=termorize_bot
    - DATABASE_HOST=mysql
    - DATABASE=termorize
    - DATABASE_USERNAME=root
    - BOT_API_KEY
    - YANDEX_TRANSLATOR_API_KEY
    - DATABASE_PASSWORD

services:
  bot:
    <<: *env
    image: trckster/termorize-bot
    command: sh -c "sleep 15 && composer migrate && php index.php"

  cron:
    <<: *env
    image: trckster/termorize-cron
    command: sh -c "sleep 15 && printenv >> /etc/environment && cron -f"

  mysql:
    image: mysql:8.3
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=termorize
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}