version: "3.9"

volumes:
  mysql-data:

services:
  bot:
    environment:
      - BOT_USERNAME=termorize_bot
      - DATABASE_HOST=mysql
      - DATABASE=termorize
      - DATABASE_USERNAME=root
      - BOT_API_KEY
      - YANDEX_TRANSLATOR_API_KEY
      - DATABASE_PASSWORD
    image: trckster/termorize
    command: sh -c "sleep 15 && composer migrate && php index.php"

  mysql:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=termorize
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}